import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "../lib/providers/ReduxProvider";
import toast, { Toaster } from 'react-hot-toast';
export const metadata: Metadata = {
  title: "Food Rush",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">   
      <body>
          <Toaster />
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
