import mongoose from "mongoose";
import express from "express";
import {getPendingResturants,updateResturantApproval,adminStats,allUsers,allDrivers} from "../controllers/adminControllers.js";
const router=express.Router();
router.get('/resturants/pending',getPendingResturants);
router.patch('/resturants/:id/approve',updateResturantApproval);
router.get('/admin/stats',adminStats);
router.get('/admin/users',allUsers);
router.get('/admin/drivers',allDrivers);
export default router;